kubescape:
  clusterName: demo-cluster
  server: api.armosec.io
  account: d6b0d1ee-4027-4124-bb7c-73ebd3d3e447
  alertCRD:
    installDefault: true
  capabilities:
    manageWorkloads: enable
    nodeProfileService: enable
    runtimeDetection: enable
  imagePullSecret:
    password: Q5UMRCFPRAHAIRWAYTOP7P4PK9ZNV2H26JFTB70CMNZ2KG1NHGPYXK6PNPNC677E
    server: quay.io
    username: armosec+armosec_ro
  imagePullSecrets: armosec-readonly
  nodeAgent:
    image:
      repository: quay.io/armosec/node-agent
      tag: v0.0.57
    resources:
      limits:
        memory: 1000Mi