kubescape:
  clusterName: demo-cluster
  server: api.armosec.io
  credentials:
    cloudSecret: cloud-secret
  alertCRD:
    installDefault: true
  capabilities:
    manageWorkloads: enable
    nodeProfileService: enable
    runtimeDetection: enable
  imagePullSecret:
    password: <set_the_password>
    server: quay.io
    username: armosec+armosec_ro
  imagePullSecrets: armosec-readonly
  nodeAgent:
    image:
      repository: quay.io/armosec/node-agent
      tag: v0.0.57
    resources:
      limits:
        memory: 1000Mi