apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: armo-ebpf-check
  labels:
    app: armo-ebpf-check
spec:
  selector:
    matchLabels:
      app: armo-ebpf-check
  template:
    metadata:
      labels:
        app: armo-ebpf-check
    spec:
      containers:
      - name: armo-ebpf-check
        image: busybox
        volumeMounts:
        - mountPath: /host
          name: host
        command:
        - /bin/sh
        - -c
        - |
          #!/bin/sh
          if grep '^CONFIG_BPF=y$' /host/boot/config-$(uname -r) && \
            grep '^CONFIG_BPF_SYSCALL=y$' /host/boot/config-$(uname -r) && \
            grep '^CONFIG_DEBUG_INFO_BTF=y$' /host/boot/config-$(uname -r); then
            echo "eBPF is supported on $(hostname)"
          else
            echo "eBPF is not supported on $(hostname)"
          fi
          touch /tmp/ready
          sleep 3600
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - test -f /tmp/ready
          initialDelaySeconds: 1
          periodSeconds: 5
      volumes:
      - name: host
        hostPath:
          path: /
      restartPolicy: Always
