apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: vulnerable-app
  name: vulnerable-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vulnerable-app