apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
  namespace: argocd
spec:
  destination:
    namespace: kubescape
    server: https://kubernetes.default.svc
  source:
    helm:
      valueFiles:
        - values/kubescape-values.yaml
      parameters:
        - name: clusterName
          value: 'demo-cluster-new'
          required: true
          type: string
    repoURL: 'https://github.com/kubescape/helm-charts'
    targetRevision: main
    path: charts/kubescape-operator
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: core
      kind: ConfigMap
      name: ks-cloud-config
      namespace: kubescape
      jsonPointers:
        - /data
        - /metadata
    - group: batch
      kind: CronJob
      name: kubescape-scheduler
      jsonPointers:
        - /spec/schedule
    - group: batch
      kind: CronJob
      name: kubevuln-scheduler
      jsonPointers:
        - /spec/schedule
