apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
  namespace: kubescape
spec:
  destination:
    namespace: kubescape
    server: https://kubernetes.default.svc
  source:
    helm:
      valueFiles:
        - values.yaml
    repoURL: "https://github.com/armosec/armo-platform-tools.git"
    targetRevision: dev
    path: demo-cluster/environments/production/kubescape
  project: default
