apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
  namespace: argocd
spec:
  destination:
    namespace: kubescape
    server: https://kubernetes.default.svc
  source:
    helm:
      valueFiles:
        - values.yaml
        - original-values.yaml
    repoURL: "https://github.com/armosec/armo-platform-tools.git"
    targetRevision: dev
    path: demo-cluster/environments/production/kubescape
  project: default
  ignoreDifferences:
    - group: core
      kind: ConfigMap
      name: ks-cloud-config
      namespace: kubescape
      jsonPointers:
        - /data
        - /metadata