apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
  namespace: argocd
spec:
  destination:
    namespace: kubescape
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubescape.github.io/helm-charts/
    chart: "kubescape-operator"
    targetRevision: x.x.x
    helm:
      valueFiles:
        - "https://raw.githubusercontent.com/armosec/armo-platform-tools/main/demo-cluster/environments/production/kubescape/values.yaml"
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: core
      kind: ConfigMap
      name: ks-cloud-config
      namespace: kubescape
      jsonPointers:
        - /data
        - /metadata
    - group: batch
      kind: CronJob
      name: kubescape-scheduler
      jsonPointers:
        - /spec/schedule
    - group: batch
      kind: CronJob
      name: kubevuln-scheduler
      jsonPointers:
        - /spec/schedule
