apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vulnerable-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/armosec/armo-platform-tools.git"
    targetRevision: dev
    path: demo-cluster/environments/production/applications/vulnerable-app
  destination:
    server: https://kubernetes.default.svc
    namespace: vulnerable-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
