apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy: {}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        kubescape.io/max-sniffing-time: ${LEARNING_PERIOD}
    spec:
      containers:
      - image: busybox
        tty: true
        name: busybox
        resources: {}