apiVersion: v1
kind: Pod
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
    kubescape.io/max-sniffing-time: ${LEARNING_PERIOD}
spec:
  containers:
  - name: ${APP_NAME}
    image: docker.io/amitschendel/ping-app:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  selector:
    app: ${APP_NAME}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${APP_NAME}-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${APP_NAME}-role-binding
subjects:
- kind: ServiceAccount
  name: "default"
roleRef:
  kind: Role
  name: ${APP_NAME}-role
  apiGroup: rbac.authorization.k8s.io
