apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy: {}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        kubescape.io/max-sniffing-time: ${LEARNING_PERIOD}
    spec:
      containers:
      - image: ubuntu:latest
        tty: true             # Allows terminal access
        stdin: true           # Keep stdin open for interaction
        name: ${APP_NAME}-container
        securityContext:
          privileged: true    # To allow sudo to work
        command: ["/bin/bash", "-c", "apt-get update && apt-get install -y sudo && while true; do sleep 1000; done"]
        resources: {}
        env:
        - name: LEARNING_PERIOD
          value: "${LEARNING_PERIOD}"