name: Build and push Docker image to GitHub Container Registry
on: [push, pull_request]

jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash

      - name: Run NSA Compliance scan
        run: |
          $HOME/.kubescape/bin/kubescape scan framework nsa \
            ./poc-prerequisite/kubescape-sizing-checker/k8s-manifest.yaml \
            --fail-threshold 80 \
            --severity-threshold high
            --format sarif
            --output results-nsa.sarif

      - name: Run Kubescape to scan image
        run: |
          $HOME/.kubescape/bin/kubescape scan image alpine:latest \
            --severity-threshold critical \
            --format sarif \
            --output results.sarif

      - name: Upload NSA Compliance scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results-nsa.sarif

      - name: Upload image scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif